const DOCTOR_CARDIOLOGIST = 'DOCTOR_CARDIOLOGIST';
const DOCTOR_DENTIST = 'DOCTOR_DENTIST';
const DOCTOR_THERAPIST = 'DOCTOR_THERAPIST';
const GOAL_CHECKUP = "GOAL_CHECKUP";
const GOAL_RECHECK = "GOAL_RECHECK";
const GOAL_SICKNESS = "GOAL_SICKNESS";
